export interface EmailTemplateCatalogItem {
    id: string;
    name: string;
    trigger: string;
    summary: string;
    audience: string;
    variables: string[];
    accentClass: string;
    previewImagePath: string;
    allowDisable: boolean;
}

export const emailTemplateCatalog: EmailTemplateCatalogItem[] = [
    {
        id: "register-success",
        name: "Welcome Email",
        trigger: "Successful account registration",
        summary: "Greets the player, highlights core actions, and drives them back into the product.",
        audience: "All newly registered users",
        variables: ["platformName", "username", "siteUrl"],
        accentClass: "border-emerald-500/20 bg-emerald-500/10 text-emerald-300",
        previewImagePath: "/sports-hero-banner.png",
        allowDisable: true,
    },
    {
        id: "deposit-success",
        name: "Deposit Confirmation",
        trigger: "Approved deposit transaction",
        summary: "Confirms wallet credit, amount, and timestamp with a strong play-again CTA.",
        audience: "Users with successful fiat or crypto deposits",
        variables: ["platformName", "username", "amountLabel", "processedAt", "siteUrl"],
        accentClass: "border-blue-500/20 bg-blue-500/10 text-blue-300",
        previewImagePath: "/home/casino.png",
        allowDisable: true,
    },
    {
        id: "withdrawal-success",
        name: "Withdrawal Processed",
        trigger: "Approved and dispatched withdrawal",
        summary: "Communicates the processed payout, expected arrival window, and support guidance.",
        audience: "Users with completed withdrawals",
        variables: ["platformName", "username", "amountLabel", "processedAt", "siteUrl"],
        accentClass: "border-violet-500/20 bg-violet-500/10 text-violet-300",
        previewImagePath: "/sports-hero-banner.png",
        allowDisable: true,
    },
    {
        id: "withdrawal-pending",
        name: "Withdrawal Pending",
        trigger: "User submits a withdrawal request",
        summary: "Confirms the withdrawal request was received and is awaiting review by the team.",
        audience: "Users who initiate a withdrawal",
        variables: ["platformName", "username", "amountLabel", "processedAt", "siteUrl"],
        accentClass: "border-yellow-500/20 bg-yellow-500/10 text-yellow-300",
        previewImagePath: "/sports-hero-banner.png",
        allowDisable: true,
    },
    {
        id: "withdrawal-processed",
        name: "Withdrawal Processing",
        trigger: "Admin moves withdrawal to processing",
        summary: "Notifies the user their withdrawal is being actively processed and approval is imminent.",
        audience: "Users with withdrawals under review",
        variables: ["platformName", "username", "amountLabel", "processedAt", "siteUrl"],
        accentClass: "border-cyan-500/20 bg-cyan-500/10 text-cyan-300",
        previewImagePath: "/sports-hero-banner.png",
        allowDisable: true,
    },
    {
        id: "withdrawal-approved",
        name: "Withdrawal Approved",
        trigger: "Admin approves the withdrawal for payout",
        summary: "Confirms the withdrawal has been approved and funds are being dispatched to the payment method.",
        audience: "Users with approved withdrawals",
        variables: ["platformName", "username", "amountLabel", "processedAt", "siteUrl"],
        accentClass: "border-emerald-500/20 bg-emerald-500/10 text-emerald-300",
        previewImagePath: "/sports-hero-banner.png",
        allowDisable: true,
    },
    {
        id: "account-suspended",
        name: "Account Suspended",
        trigger: "Admin bans or suspends a user",
        summary: "Notifies the user their account has been suspended with reason, impact details, and support contact.",
        audience: "Users whose accounts are banned by admin",
        variables: ["platformName", "username", "reason", "suspendedAt", "siteUrl"],
        accentClass: "border-red-500/20 bg-red-500/10 text-red-300",
        previewImagePath: "",
        allowDisable: true,
    },
    {
        id: "bonus-credited",
        name: "Bonus Credited",
        trigger: "Promo code redeemed or admin bonus granted",
        summary: "Confirms the bonus amount, wallet, wagering requirement, and code used.",
        audience: "Users who receive a bonus credit",
        variables: ["platformName", "username", "amountLabel", "walletLabel", "wageringRequired", "bonusCode", "creditedAt", "siteUrl"],
        accentClass: "border-amber-500/20 bg-amber-500/10 text-amber-300",
        previewImagePath: "",
        allowDisable: true,
    },
    {
        id: "bonus-wagered",
        name: "Wagering Complete",
        trigger: "User completes bonus wagering requirement",
        summary: "Notifies the user that their bonus wagering is complete and ready for conversion.",
        audience: "Users who fulfill bonus wagering",
        variables: ["platformName", "username", "bonusTitle", "bonusAmount", "completedAt", "siteUrl"],
        accentClass: "border-lime-500/20 bg-lime-500/10 text-lime-300",
        previewImagePath: "",
        allowDisable: true,
    },
    {
        id: "bet-refund",
        name: "Bet Refund (Early Six)",
        trigger: "Admin clicks Refund Eligible Bets on an Early Six promotion",
        summary: "Notifies the user that their Match Odds bet has been refunded due to early six market void.",
        audience: "Users whose qualifying bets are refunded",
        variables: ["platformName", "username", "amountLabel", "eventName", "marketName", "refundedAt", "siteUrl"],
        accentClass: "border-sky-500/20 bg-sky-500/10 text-sky-300",
        previewImagePath: "",
        allowDisable: true,
    },
    {
        id: "forgot-password",
        name: "Password Reset",
        trigger: "Forgot password request",
        summary: "Sends the secure reset link with expiry guidance and fallback URL text.",
        audience: "Users requesting a password reset",
        variables: ["platformName", "username", "resetLink", "siteUrl"],
        accentClass: "border-amber-500/20 bg-amber-500/10 text-amber-300",
        previewImagePath: "/sports-hero-banner.png",
        allowDisable: false,
    },
    {
        id: "otp",
        name: "OTP Verification",
        trigger: "Email verification and account security flows",
        summary: "Delivers one-time verification codes for registration, password reset, and email-binding actions.",
        audience: "Users completing secure email verification",
        variables: ["platformName", "otpCode", "purposeLabel", "purposeAction", "siteUrl"],
        accentClass: "border-orange-500/20 bg-orange-500/10 text-orange-300",
        previewImagePath: "/sports-hero-banner.png",
        allowDisable: false,
    },
    {
        id: "smtp-test",
        name: "SMTP Test Email",
        trigger: "Manual SMTP connectivity test",
        summary: "Confirms sender identity, relay health, and branded rendering before live traffic is enabled.",
        audience: "Internal operators validating SMTP setup",
        variables: ["platformName", "senderEmail", "siteUrl"],
        accentClass: "border-sky-500/20 bg-sky-500/10 text-sky-300",
        previewImagePath: "/sports-hero-banner.png",
        allowDisable: false,
    },
];

export const emailLaunchChecklist = [
    "Configure SMTP host, port, sender name, and sender email in Site Config.",
    "Send a test email from Site Config before enabling live campaigns.",
    "Review transactional templates so copy, image art, and CTA links match the active brand.",
    "Keep welcome, deposit, and withdrawal notifications enabled for player lifecycle coverage.",
    "Use WhatsApp broadcasts for outbound bulk messaging until email campaign automation is added.",
];
